#Deployment  Format created by Krishnendu Bhowmick
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pythondeploymentdemo
  labels:
    app:  pythondeployment
spec:
  selector:
    matchLabels:
      app: pythondeployment
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  pythondeployment
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  pythondeploymentpod
        image:  krishhub/django-hello-app:tagVersion
        ports:
        - containerPort:  8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pythondeploymentsvc
spec:
  selector:
    app: pythondeployment
  type: NodePort
  ports:
  - name: pythondeploymentsvcport
    protocol: TCP
    port: 80
    targetPort: 8000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30020